import json
from pathlib import Path

from scripts.generate_support_matrix import render_support_matrix


def test_support_matrix_is_generated_from_smoke_statuses():
    required = json.loads(Path("tests/fixtures/release_required_rows_v2.json").read_text(encoding="utf-8"))["rows"]
    smoke = {
        "tag": "v9.9.9",
        "manual_matrix": {
            "win11_clean_no_python_setup": "pass",
            "provider_smoke": {
                "nvidia_cuda_torch_onnx_faster_whisper_llama": "blocked",
                "torch_cuda_tensor_smoke": "pass",
            },
        },
    }

    matrix = render_support_matrix(smoke, required[:1])

    assert "generated by scripts/generate_support_matrix.py" in matrix
    assert "Source smoke artifact: `v9.9.9`." in matrix
    assert "Required release rows: 1/1 pass." in matrix
    assert "| NVIDIA CUDA provider stack | Blocked |" in matrix
    assert "`nvidia_cuda_torch_onnx_faster_whisper_llama`: blocked" in matrix
    assert "`win11_clean_no_python_setup`: pass" in matrix


def test_committed_support_matrix_matches_generator():
    smoke_path = Path("release-smoke-v0.4.0.json")
    generated_path = Path("docs/support_matrix.generated.md")
    if not smoke_path.exists() or not generated_path.exists():
        return
    required = json.loads(Path("tests/fixtures/release_required_rows_v2.json").read_text(encoding="utf-8"))["rows"]
    smoke = json.loads(smoke_path.read_text(encoding="utf-8"))

    assert generated_path.read_text(encoding="utf-8") == render_support_matrix(smoke, required)
