from __future__ import annotations

from .common import RowDefinition


LOCAL_BLOCKED_MODULE = "qa.runtime_matrix.rows.blocked_external"


def row(row_id: str, module: str = LOCAL_BLOCKED_MODULE, description: str = "", *, required: bool = False, hardware: str = "local") -> RowDefinition:
    return RowDefinition(row_id=row_id, module=module, description=description or row_id.replace("_", " "), required=required, hardware=hardware)


ROWS: dict[str, RowDefinition] = {
    "windows_vc_runtime": row("windows_vc_runtime", "qa.runtime_matrix.rows.windows_vc_runtime"),
    "windows_vc_runtime_repair_contract": row("windows_vc_runtime_repair_contract", "qa.runtime_matrix.rows.windows_vc_runtime"),
    "windows_directml_provider": row("windows_directml_provider", "qa.runtime_matrix.rows.windows_directml_provider"),
    "directml_provider_conflict_repair": row("directml_provider_conflict_repair", "qa.runtime_matrix.rows.windows_directml_provider"),
    "windows_vulkan_runtime": row("windows_vulkan_runtime", "qa.runtime_matrix.rows.windows_vulkan_runtime"),
    "win11_clean_no_python_setup": row("win11_clean_no_python_setup", "qa.runtime_matrix.rows.setup_environment", hardware="clean_windows_vm"),
    "clean_vm_zero_dependency_bootstrap": row("clean_vm_zero_dependency_bootstrap", "qa.runtime_matrix.rows.clean_vm_bootstrap", hardware="clean_windows_vm"),
    "win10_existing_python_setup": row("win10_existing_python_setup", "qa.runtime_matrix.rows.setup_environment", hardware="win10_vm"),
    "first_run_smoke_json": row("first_run_smoke_json", "qa.runtime_matrix.rows.setup_environment"),
    "install_path_with_spaces": row("install_path_with_spaces", "qa.runtime_matrix.rows.installer_validation"),
    "setup_verify_release_bad_checksum": row("setup_verify_release_bad_checksum", "qa.runtime_matrix.rows.installer_validation"),
    "setup_double_click_equivalent": row("setup_double_click_equivalent", "qa.runtime_matrix.rows.setup_environment", hardware="interactive_windows_shell"),
    "setup_dry_run_verify_release": row("setup_dry_run_verify_release", "qa.runtime_matrix.rows.installer_validation"),
    "setup_doctor_strict": row("setup_doctor_strict", "qa.runtime_matrix.rows.installer_validation"),
    "setup_repair_all_safe": row("setup_repair_all_safe", "qa.runtime_matrix.rows.installer_validation"),
    "setup_repair_model_layouts": row("setup_repair_model_layouts", "qa.runtime_matrix.rows.installer_validation"),
    "update_preserves_user_data": row("update_preserves_user_data", "qa.runtime_matrix.rows.installer_validation"),
    "repair_broken_venv": row("repair_broken_venv", "qa.runtime_matrix.rows.installer_validation"),
    "uninstall_preserve_user_data": row("uninstall_preserve_user_data", "qa.runtime_matrix.rows.installer_validation"),
    "destructive_uninstall_requires_phrase": row("destructive_uninstall_requires_phrase", "qa.runtime_matrix.rows.installer_validation"),
    "bad_checksum_fails_before_execution": row("bad_checksum_fails_before_execution", "qa.runtime_matrix.rows.installer_validation"),
    "tampered_installer_fails_before_execution": row("tampered_installer_fails_before_execution", "qa.runtime_matrix.rows.installer_validation"),
    "interrupted_download_rollback": row("interrupted_download_rollback", "qa.runtime_matrix.rows.installer_validation"),
    "broken_venv_repair": row("broken_venv_repair", "qa.runtime_matrix.rows.installer_validation"),
    "empty_models_folder": row("empty_models_folder", "qa.runtime_matrix.rows.model_folder_scanner"),
    "empty_models": row("empty_models", "qa.runtime_matrix.rows.model_folder_scanner"),
    "nested_models_folders": row("nested_models_folders", "qa.runtime_matrix.rows.model_folder_scanner"),
    "nested_models_scan": row("nested_models_scan", "qa.runtime_matrix.rows.model_folder_scanner"),
    "wav_mp3_mp4_no_audio_corrupt_media": row("wav_mp3_mp4_no_audio_corrupt_media", "qa.runtime_matrix.rows.media_fixtures"),
    "wav_mp3_mp4_media": row("wav_mp3_mp4_media", "qa.runtime_matrix.rows.media_fixtures"),
    "corrupt_media_readable_error": row("corrupt_media_readable_error", "qa.runtime_matrix.rows.media_fixtures"),
    "no_audio_video_readable_error": row("no_audio_video_readable_error", "qa.runtime_matrix.rows.media_fixtures"),
    "real_media_download_cache": row("real_media_download_cache", "qa.runtime_matrix.rows.real_media_download_cache", hardware="network"),
    "hf_downloader_qwen3_asr_gguf_mmproj_layout": row("hf_downloader_qwen3_asr_gguf_mmproj_layout", "qa.runtime_matrix.rows.hf_downloader_layouts"),
    "hf_downloader_qwen3_asr_gguf_mmproj_public_listing": row("hf_downloader_qwen3_asr_gguf_mmproj_public_listing", "qa.runtime_matrix.rows.hf_downloader_layouts", hardware="network"),
    "hf_downloader_qwen3_asr_gguf_mmproj_cached_materialization": row("hf_downloader_qwen3_asr_gguf_mmproj_cached_materialization", "qa.runtime_matrix.rows.hf_downloader_layouts"),
    "hf_downloader_qwen3_asr_gguf_mmproj_noninteractive_flow": row("hf_downloader_qwen3_asr_gguf_mmproj_noninteractive_flow", "qa.runtime_matrix.rows.hf_downloader_layouts"),
    "hf_downloader_qwen3_asr_gguf_mmproj_public_noninteractive_flow": row("hf_downloader_qwen3_asr_gguf_mmproj_public_noninteractive_flow", "qa.runtime_matrix.rows.hf_downloader_layouts", hardware="network"),
    "hf_downloader_qwen3_asr_gguf_mmproj_public_download_to_asr": row("hf_downloader_qwen3_asr_gguf_mmproj_public_download_to_asr", "qa.runtime_matrix.rows.hf_downloader_layouts", hardware="network"),
    "hf_downloader_qwen3_asr_gguf_mmproj_public_real_download_to_asr": row("hf_downloader_qwen3_asr_gguf_mmproj_public_real_download_to_asr", "qa.runtime_matrix.rows.hf_downloader_layouts", hardware="network"),
    "hf_downloader_supported_outcome_taxonomy": row("hf_downloader_supported_outcome_taxonomy", "qa.runtime_matrix.rows.hf_downloader_layouts"),
    "same_media_multi_model_smollm_benchmark": row("same_media_multi_model_smollm_benchmark", "qa.runtime_matrix.rows.same_media_multi_model_smollm_benchmark"),
    "same_media_multi_model_smollm_benchmark_directml": row("same_media_multi_model_smollm_benchmark_directml", "qa.runtime_matrix.rows.same_media_multi_model_smollm_benchmark", hardware="directml"),
    "compare_html_offline_large_transcript": row("compare_html_offline_large_transcript", "qa.runtime_matrix.rows.report_reference_validation"),
    "compare_html_offline": row("compare_html_offline", "qa.runtime_matrix.rows.report_reference_validation"),
    "batch_continues_after_one_model_or_chunk_fails": row("batch_continues_after_one_model_or_chunk_fails", "qa.runtime_matrix.rows.failure_isolation"),
    "one_model_failure_continues": row("one_model_failure_continues", "qa.runtime_matrix.rows.failure_isolation"),
    "one_chunk_failure_continues": row("one_chunk_failure_continues", "qa.runtime_matrix.rows.failure_isolation"),
    "llm_reference_json_import": row("llm_reference_json_import", "qa.runtime_matrix.rows.report_reference_validation"),
    "dependency_install_declined": row("dependency_install_declined", "qa.runtime_matrix.rows.failure_isolation"),
    "dependency_install_accepted": row("dependency_install_accepted", "qa.runtime_matrix.rows.failure_isolation"),
    "cpu_model_smoke": row("cpu_model_smoke", "qa.runtime_matrix.rows.real_tiny_faster_whisper_report_smoke"),
    "nvidia_cuda_torch_onnx_faster_whisper_llama": row("nvidia_cuda_torch_onnx_faster_whisper_llama", "qa.runtime_matrix.rows.cuda_provider_matrix", hardware="nvidia_cuda"),
    "nvidia_cuda_hardware_detection": row("nvidia_cuda_hardware_detection", "qa.runtime_matrix.rows.cuda_provider_matrix", hardware="nvidia_cuda"),
    "torch_cuda_tensor_smoke": row("torch_cuda_tensor_smoke", "qa.runtime_matrix.rows.cuda_provider_matrix", hardware="nvidia_cuda"),
    "onnxruntime_cuda_tiny_session": row("onnxruntime_cuda_tiny_session", "qa.runtime_matrix.rows.cuda_provider_matrix", hardware="nvidia_cuda"),
    "faster_whisper_ctranslate2_cuda_smoke": row("faster_whisper_ctranslate2_cuda_smoke", "qa.runtime_matrix.rows.cuda_provider_matrix", hardware="nvidia_cuda"),
    "llama_cpp_cuda_smollm_smoke": row("llama_cpp_cuda_smollm_smoke", "qa.runtime_matrix.rows.cuda_provider_matrix", hardware="nvidia_cuda"),
    "llama_cpp_vulkan_smollm_smoke": row("llama_cpp_vulkan_smollm_smoke", "qa.runtime_matrix.rows.windows_vulkan_runtime", hardware="vulkan"),
    "amd_directml_onnx_smoke": row("amd_directml_onnx_smoke", "qa.runtime_matrix.rows.generic_onnx_ctc_tiny", hardware="directml"),
    "intel_directml_onnx_smoke": row("intel_directml_onnx_smoke", "qa.runtime_matrix.rows.generic_onnx_ctc_tiny", hardware="intel_directml"),
    "intel_openvino_onnx_smoke": row("intel_openvino_onnx_smoke", "qa.runtime_matrix.rows.generic_onnx_ctc_tiny", hardware="intel_openvino"),
    "vulkan_runtime_no_sdk": row("vulkan_runtime_no_sdk", "qa.runtime_matrix.rows.windows_vulkan_runtime", hardware="vulkan_no_sdk"),
    "vulkan_runtime_with_sdk": row("vulkan_runtime_with_sdk", "qa.runtime_matrix.rows.windows_vulkan_runtime", hardware="vulkan_sdk"),
    "hf_safetensors_asr": row("hf_safetensors_asr", "qa.runtime_matrix.rows.hf_safetensors_tiny"),
    "hf_whisper_safetensors": row("hf_whisper_safetensors", "qa.runtime_matrix.rows.hf_safetensors_tiny"),
    "hf_whisper_safetensors_cpu": row("hf_whisper_safetensors_cpu", "qa.runtime_matrix.rows.hf_safetensors_tiny"),
    "hf_whisper_safetensors_smollm_grading_cpu": row("hf_whisper_safetensors_smollm_grading_cpu", "qa.runtime_matrix.rows.hf_safetensors_smollm_grading"),
    "hf_whisper_sharded_safetensors_smollm_grading_cpu": row("hf_whisper_sharded_safetensors_smollm_grading_cpu", "qa.runtime_matrix.rows.hf_safetensors_smollm_grading"),
    "hf_whisper_safetensors_quality_smollm_grading_cpu": row("hf_whisper_safetensors_quality_smollm_grading_cpu", "qa.runtime_matrix.rows.hf_safetensors_smollm_grading"),
    "hf_safetensors_asr_smollm_grading_cpu": row("hf_safetensors_asr_smollm_grading_cpu", "qa.runtime_matrix.rows.hf_safetensors_smollm_grading"),
    "hf_safetensors_asr_quality_smollm_grading_cpu": row("hf_safetensors_asr_quality_smollm_grading_cpu", "qa.runtime_matrix.rows.hf_safetensors_smollm_grading"),
    "sharded_safetensors_index": row("sharded_safetensors_index", "qa.runtime_matrix.rows.safetensors_classification"),
    "faster_whisper_ctranslate2": row("faster_whisper_ctranslate2", "qa.runtime_matrix.rows.ctranslate2_dynamic_resolver"),
    "faster_whisper_pkg_resources_repair": row("faster_whisper_pkg_resources_repair", "qa.runtime_matrix.rows.ctranslate2_dynamic_resolver"),
    "real_tiny_faster_whisper_report_smoke": row("real_tiny_faster_whisper_report_smoke", "qa.runtime_matrix.rows.real_tiny_faster_whisper_report_smoke"),
    "faster_whisper_cpu": row("faster_whisper_cpu", "qa.runtime_matrix.rows.real_tiny_faster_whisper_report_smoke"),
    "real_tiny_faster_whisper_smollm_grading": row("real_tiny_faster_whisper_smollm_grading", "qa.runtime_matrix.rows.real_faster_whisper_smollm_grading"),
    "faster_whisper_cuda_unavailable_cpu_fallback": row("faster_whisper_cuda_unavailable_cpu_fallback", "qa.runtime_matrix.rows.cuda_provider_matrix"),
    "whisper_cpp_ggml": row("whisper_cpp_ggml", "qa.runtime_matrix.rows.whisper_cpp_ggml"),
    "whisper_cpp_ggml_smollm_grading": row("whisper_cpp_ggml_smollm_grading", "qa.runtime_matrix.rows.whisper_cpp_smollm_grading"),
    "whisper_cpp_ggml_speech_smollm_grading": row("whisper_cpp_ggml_speech_smollm_grading", "qa.runtime_matrix.rows.whisper_cpp_smollm_grading"),
    "openai_whisper_pt_checksum_verified": row("openai_whisper_pt_checksum_verified", "qa.runtime_matrix.rows.openai_whisper_pt_safety"),
    "openai_whisper_pt_unknown_blocked": row("openai_whisper_pt_unknown_blocked", "qa.runtime_matrix.rows.openai_whisper_pt_safety"),
    "openai_pt_unverified_blocked": row("openai_pt_unverified_blocked", "qa.runtime_matrix.rows.openai_whisper_pt_safety"),
    "generic_onnx_ctc_manifest_v1": row("generic_onnx_ctc_manifest_v1", "qa.runtime_matrix.rows.generic_onnx_ctc_tiny"),
    "generic_onnx_manifest_cpu": row("generic_onnx_manifest_cpu", "qa.runtime_matrix.rows.generic_onnx_ctc_tiny"),
    "generic_onnx_smollm_grading_cpu": row("generic_onnx_smollm_grading_cpu", "qa.runtime_matrix.rows.generic_onnx_smollm_grading"),
    "generic_onnx_smollm_grading_directml": row("generic_onnx_smollm_grading_directml", "qa.runtime_matrix.rows.generic_onnx_smollm_grading", hardware="directml"),
    "generic_onnx_ctc_quality_smollm_grading_cpu": row("generic_onnx_ctc_quality_smollm_grading_cpu", "qa.runtime_matrix.rows.generic_onnx_smollm_grading"),
    "generic_onnx_without_manifest_rejected": row("generic_onnx_without_manifest_rejected", "qa.runtime_matrix.rows.generic_onnx_ctc_tiny"),
    "multi_file_onnx_ar_nar": row("multi_file_onnx_ar_nar", "qa.runtime_matrix.rows.multi_file_onnx_ar_nar"),
    "audio_asr_gguf_mmproj": row("audio_asr_gguf_mmproj", "qa.runtime_matrix.rows.gguf_asr_mmproj", hardware="asr_gguf_mmproj_fixture"),
    "gguf_asr_mmproj_pair": row("gguf_asr_mmproj_pair", "qa.runtime_matrix.rows.gguf_asr_mmproj", hardware="asr_gguf_mmproj_fixture"),
    "incomplete_audio_asr_gguf_mmproj_rejected": row("incomplete_audio_asr_gguf_mmproj_rejected", "qa.runtime_matrix.rows.gguf_asr_mmproj"),
    "mismatched_audio_asr_gguf_mmproj_rejected": row("mismatched_audio_asr_gguf_mmproj_rejected", "qa.runtime_matrix.rows.gguf_asr_mmproj"),
    "gguf_reference_llm": row("gguf_reference_llm", "qa.runtime_matrix.rows.gguf_reference_llm_smollm135"),
    "gguf_text_llm_reference_only": row("gguf_text_llm_reference_only", "qa.runtime_matrix.rows.gguf_reference_llm_smollm135"),
    "smollm_reference_grading_report": row("smollm_reference_grading_report", "qa.runtime_matrix.rows.smollm_reference_grading_report"),
    "standalone_safetensors_incomplete": row("standalone_safetensors_incomplete", "qa.runtime_matrix.rows.safetensors_classification"),
    "hf_text_llm_safetensors_unsupported": row("hf_text_llm_safetensors_unsupported", "qa.runtime_matrix.rows.safetensors_classification"),
    "known_unsupported_asr_families_explained": row("known_unsupported_asr_families_explained", "qa.runtime_matrix.rows.known_unsupported_asr"),
}
