from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace

from app.adapters.base import ChunkTranscript, ModelCandidate, ModelRunResult
from app.html_report_builder import build_html_report
from app.reference_import import import_llm_reference
from app import results_writer as results_writer_module
from app.results_writer import build_results, write_all_reports
from qa.runtime_matrix.common import dependency_resolution_report_failures, write_row


def _chunk(index: int) -> SimpleNamespace:
    return SimpleNamespace(
        index=index,
        start_seconds=float(index),
        end_seconds=float(index + 1),
        cut_reason="fixture",
        rms_db=-18.0,
    )


def _candidate(candidate_id: str, display_name: str, backend: str, precision: str) -> ModelCandidate:
    return ModelCandidate(
        candidate_id=candidate_id,
        display_name=display_name,
        family_name=display_name,
        backend=backend,
        container_format="fixture",
        task="automatic-speech-recognition",
        precision=precision,
        quantization_label=precision,
        path=Path("Models") / display_name,
        adapter_name=backend,
        runnable=True,
    )


def _run(candidate: ModelCandidate, chunks: list[SimpleNamespace], texts: list[str], speed: float, ram_mb: float) -> ModelRunResult:
    return ModelRunResult(
        candidate=candidate,
        transcript_chunks=[
            ChunkTranscript(
                chunk_id=f"{chunk.index + 1:04d}",
                start_seconds=chunk.start_seconds,
                end_seconds=chunk.end_seconds,
                text=texts[chunk.index],
                raw={"fixture": True},
            )
            for chunk in chunks
        ],
        metrics={
            "provider": candidate.backend,
            "audio_seconds": float(len(chunks)),
            "model_load_seconds": 0.01,
            "inference_seconds": 0.05,
            "total_wall_seconds": 0.1,
            "audio_seconds_per_wall_second": speed,
            "peak_process_memory_mb": ram_mb,
            "peak_vram_mb": 32.0,
            "vram_measurement_source": "fixture_windows_gpu_adapter_memory",
            "windows_peak_dedicated_vram_mb": 32.0,
            "torch_peak_vram_mb": None,
        },
        errors=[],
    )


def _fixture_results(evidence_dir: Path, *, chunk_count: int) -> tuple[dict, Path]:
    source = evidence_dir / "Input" / "fixture.wav"
    source.parent.mkdir(parents=True, exist_ok=True)
    source.write_bytes(b"easy-asr-bench-report-fixture")
    chunks = [_chunk(index) for index in range(chunk_count)]
    reference_texts = [f"chunk {index + 1} expected transcript" for index in range(chunk_count)]
    near_texts = list(reference_texts)
    if chunk_count:
        near_texts[-1] = near_texts[-1].replace("expected", "expcted")
    wrong_texts = [f"chunk {index + 1} wrong output" for index in range(chunk_count)]
    run_results = [
        _run(_candidate("fixture_fast", "Fixture Fast ASR", "fixture_fast", "fp32"), chunks, near_texts, 5.0, 96.0),
        _run(_candidate("fixture_wrong", "Fixture Wrong ASR", "fixture_wrong", "int8"), chunks, wrong_texts, 1.0, 512.0),
    ]
    results = build_results(
        source,
        audio_seconds=float(chunk_count),
        chunks=chunks,
        run_results=run_results,
        unsupported_models=[],
        media_seconds=0.01,
    )
    output_dir = write_all_reports(results, evidence_dir / "Output")
    return results, output_dir


def _reference_for(results: dict) -> dict:
    return {
        "schema": "easy_asr_bench.llm_reference.v1",
        "source_sha256": results["source"]["sha256"],
        "reference_type": "llm_corrected_reference",
        "segments": [
            {
                "chunk_id": chunk["chunk_id"],
                "start_seconds": chunk["start_seconds"],
                "end_seconds": chunk["end_seconds"],
                "text": f"chunk {index + 1} expected transcript",
                "uncertain": [],
            }
            for index, chunk in enumerate(results["chunk_plan"]["chunks"])
        ],
        "global_notes": ["fixture reference generated by runtime-matrix row"],
    }


def _write_scored_artifacts(results: dict, output_dir: Path) -> dict:
    reference = _reference_for(results)
    scored = import_llm_reference(results, "LLM response:\n```json\n" + json.dumps(reference) + "\n```")
    scored_path = output_dir / "scored_report.json"
    scored_path.write_text(json.dumps(scored, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    scored_html = output_dir / "compare_scored.html"
    scored_html.write_text(build_html_report(scored), encoding="utf-8", newline="\n")
    return {"reference": reference, "scored": scored, "scored_path": scored_path, "scored_html": scored_html}


def _assert_report_files(output_dir: Path, *, large: bool) -> list[str]:
    failures: list[str] = []
    required = ["results.json", "results.txt", "benchmark.csv", "compare.html", "scored_report.json", "compare_scored.html"]
    for name in required:
        if not (output_dir / name).exists():
            failures.append(f"missing report artifact {name}")
    html = (output_dir / "compare.html").read_text(encoding="utf-8")
    scored_html = (output_dir / "compare_scored.html").read_text(encoding="utf-8")
    markers = [
        "<!doctype html>",
        'id="results-json"',
        "LLM-Corrected Reference",
        "Speed and Memory Only",
        "Video Memory",
        "function scoreReference",
        "function renderAlignmentPage",
    ]
    if large:
        markers.extend(["const pageSize = 25", "const transcriptPageSize = 5000", "chunks.slice(chunkPage * pageSize"])
    for marker in markers:
        if marker not in html:
            failures.append(f"compare.html missing marker {marker}")
    scored_markers = [
        "Loaded precomputed LLM-corrected reference scores",
        "precomputedReferenceScores",
        "Accuracy Rank",
        "fixture_windows_gpu_adapter_memory",
    ]
    for marker in scored_markers:
        if marker not in scored_html:
            failures.append(f"compare_scored.html missing marker {marker}")
    return failures


def _atomic_report_write_failure_cleanup(row_id: str, evidence_dir: Path) -> dict:
    results, output_dir = _fixture_results(evidence_dir, chunk_count=2)
    stable_csv = output_dir / "benchmark.csv"
    stable_csv_before = stable_csv.read_text(encoding="utf-8")
    text_target = output_dir / "atomic_text_failure.txt"
    failures = []
    original_replace = results_writer_module.Path.replace

    def failing_replace(self: Path, target: Path) -> Path:
        if self.name in {"benchmark.csv.partial", "atomic_text_failure.txt.partial"}:
            raise OSError(f"simulated replace failure for {self.name}")
        return original_replace(self, target)

    try:
        results_writer_module.Path.replace = failing_replace
        try:
            results_writer_module.write_benchmark_csv(stable_csv, results)
            failures.append("CSV write unexpectedly succeeded despite simulated replace failure")
        except OSError as exc:
            csv_error = str(exc)
        try:
            results_writer_module._atomic_write_text(text_target, "should not be visible")
            failures.append("text write unexpectedly succeeded despite simulated replace failure")
        except OSError as exc:
            text_error = str(exc)
    finally:
        results_writer_module.Path.replace = original_replace

    if stable_csv.read_text(encoding="utf-8") != stable_csv_before:
        failures.append("existing benchmark.csv changed after failed atomic replace")
    if (output_dir / "benchmark.csv.partial").exists():
        failures.append("failed CSV write left benchmark.csv.partial")
    if text_target.exists():
        failures.append("failed text write created final text target")
    if (output_dir / "atomic_text_failure.txt.partial").exists():
        failures.append("failed text write left atomic_text_failure.txt.partial")
    if "simulated replace failure" not in locals().get("csv_error", ""):
        failures.append("CSV failure did not surface the replace error")
    if "simulated replace failure" not in locals().get("text_error", ""):
        failures.append("text failure did not surface the replace error")

    return write_row(
        row_id,
        "pass" if not failures else "fail",
        evidence_dir,
        summary=(
            "Report atomic writes clean failed partial files and preserve existing artifacts."
            if not failures
            else "Report atomic write cleanup validation failed."
        ),
        details={
            "output_dir": str(output_dir),
            "csv_error": locals().get("csv_error", ""),
            "text_error": locals().get("text_error", ""),
            "stable_csv_bytes": len(stable_csv_before.encode("utf-8")),
            "failures": failures,
        },
        artifacts=[output_dir / "results.json", output_dir / "results.txt", output_dir / "benchmark.csv", output_dir / "compare.html"],
    )


def run(row_id: str, evidence_dir: Path, _install_deps: bool, _allow_downloads: bool) -> dict:
    if row_id == "report_atomic_write_failure_cleanup":
        return _atomic_report_write_failure_cleanup(row_id, evidence_dir)
    large = row_id == "compare_html_offline_large_transcript"
    chunk_count = 120 if large else 3
    results, output_dir = _fixture_results(evidence_dir, chunk_count=chunk_count)
    scored_bundle = _write_scored_artifacts(results, output_dir)
    scored = scored_bundle["scored"]
    dependency_report_failures, dependency_report_details = dependency_resolution_report_failures(results)
    failures = [*_assert_report_files(output_dir, large=large), *dependency_report_failures]
    if scored.get("status") != "scored":
        failures.append("LLM reference import did not score")
    scores = scored.get("scores", {})
    if scores.get("fixture_fast", {}).get("balanced_rank") != 1:
        failures.append("expected fixture_fast to rank first after LLM-corrected scoring")
    if scores.get("fixture_fast", {}).get("normalized_wer", 1) >= scores.get("fixture_wrong", {}).get("normalized_wer", 0):
        failures.append("expected fixture_fast to have lower normalized WER than fixture_wrong")
    if row_id == "llm_reference_json_import":
        invalid = import_llm_reference(results, {**scored_bundle["reference"], "source_sha256": "wrong"})
        if invalid.get("status") != "invalid":
            failures.append("invalid source hash reference was not rejected")
    artifacts = [
        output_dir / "results.json",
        output_dir / "results.txt",
        output_dir / "benchmark.csv",
        output_dir / "compare.html",
        scored_bundle["scored_path"],
        scored_bundle["scored_html"],
    ]
    details = {
        "output_dir": str(output_dir),
        "chunk_count": chunk_count,
        "score_status": scored.get("status"),
        "score_type": scored.get("score_type"),
        "scores": {
            candidate_id: {
                "normalized_wer": score.get("normalized_wer"),
                "balanced_score": score.get("balanced_score"),
                "balanced_rank": score.get("balanced_rank"),
                "alignment_mode": score.get("alignment_mode"),
            }
            for candidate_id, score in scores.items()
        },
        "failures": failures,
        **dependency_report_details,
    }
    return write_row(
        row_id,
        "pass" if not failures else "fail",
        evidence_dir,
        summary=(
            "Offline reports and LLM-corrected reference scoring artifacts were generated and validated."
            if not failures
            else "Offline report/reference validation failed."
        ),
        details=details,
        artifacts=artifacts,
    )
