from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


SUPPORT_CLAIMS: list[tuple[str, list[str]]] = [
    ("Clean Windows bootstrap and installed-app first run", ["win11_clean_no_python_setup", "windows_sandbox_clean_bootstrap_deploy", "clean_vm_zero_dependency_bootstrap", "win10_existing_python_setup", "first_run_smoke_json"]),
    ("Release installer integrity and dry-run verification", ["install_path_with_spaces", "setup_dry_run_json", "setup_dry_run_verify_release", "setup_verify_release_bad_checksum", "bad_checksum_fails_before_execution", "tampered_installer_fails_before_execution"]),
    ("Safe dependency repair and recovery", ["setup_doctor_strict", "setup_repair_all_safe", "repair_all_safe_failure_isolation", "repair_all_safe_stale_cached_resolution", "repair_plan_issue_classification_contract", "repair_broken_venv"]),
    ("Hugging Face Safetensors ASR on CPU", ["hf_whisper_safetensors_cpu", "hf_whisper_safetensors_quality_smollm_grading_cpu", "hf_safetensors_asr_quality_smollm_grading_cpu", "hf_whisper_sharded_safetensors_smollm_grading_cpu"]),
    ("faster-whisper CPU and repair paths", ["faster_whisper_cpu", "faster_whisper_pkg_resources_repair", "faster_whisper_ctranslate2_candidate_fallback_repair", "faster_whisper_vc_runtime_repair"]),
    ("faster-whisper CUDA requested-unavailable fallback", ["faster_whisper_cuda_unavailable_cpu_fallback"]),
    ("OpenAI Whisper .pt with checksum safety", ["openai_whisper_pt_checksum_verified", "openai_pt_unverified_blocked", "openai_whisper_cuda_unavailable_cpu_fallback"]),
    ("whisper.cpp GGML CPU path", ["whisper_cpp_ggml_speech_smollm_grading", "real_public_video_whisper_cpp_ggml_smollm_grading"]),
    ("Generic ONNX CTC CPU and manifest safety", ["intel_cpu_onnx_smoke", "generic_onnx_manifest_cpu", "generic_onnx_without_manifest_rejected", "real_public_video_generic_onnx_ctc_smollm_grading_cpu"]),
    ("Generic ONNX DirectML/OpenVINO provider paths", ["amd_directml_onnx_smoke", "intel_directml_onnx_smoke", "intel_openvino_onnx_smoke", "same_media_multi_model_smollm_benchmark_directml"]),
    ("NVIDIA CUDA provider stack", ["nvidia_cuda_torch_onnx_faster_whisper_llama", "torch_cuda_tensor_smoke", "onnxruntime_cuda_tiny_session", "faster_whisper_ctranslate2_cuda_smoke", "llama_cpp_cuda_smollm_smoke"]),
    ("GGUF text reference LLM", ["gguf_text_llm_reference_only", "llama_mtmd_dependency_repair_contract"]),
    ("GGUF ASR plus projector package", ["gguf_asr_mmproj_pair", "mismatched_audio_asr_gguf_mmproj_rejected"]),
    ("llama.cpp Vulkan provider path", ["vulkan_runtime_no_sdk", "vulkan_runtime_with_sdk", "llama_cpp_vulkan_smollm_smoke"]),
    ("Media handling and report UX", ["wav_mp3_mp4_media", "corrupt_media_readable_error", "no_audio_video_readable_error", "compare_html_offline", "compare_html_offline_large_transcript", "real_public_folder_batch_smollm_benchmark"]),
    ("Failure isolation and queue safety", ["one_model_failure_continues", "one_chunk_failure_continues", "report_atomic_write_failure_cleanup", "watched_folder_partial_write_queue_contract", "dependency_install_declined"]),
]


def _flatten_manual_matrix(node: dict[str, Any]) -> dict[str, str]:
    rows: dict[str, str] = {}
    for key, value in node.items():
        if isinstance(value, dict) and value.get("schema") == "easy_asr_bench.runtime_matrix.row.v1":
            rows[key] = str(value.get("status", "unknown"))
        elif isinstance(value, dict):
            rows.update(_flatten_manual_matrix(value))
        else:
            rows[key] = str(value)
    return rows


def _claim_status(statuses: list[str]) -> str:
    normalized = [status.lower() for status in statuses]
    if normalized and all(status == "pass" for status in normalized):
        return "Verified"
    if any(status == "fail" for status in normalized):
        return "Failed"
    if any(status == "blocked" for status in normalized):
        return "Blocked"
    return "Not verified"


def _row_summary(rows: list[str], statuses: dict[str, str]) -> str:
    return "<br>".join(f"`{row}`: {statuses.get(row, 'missing')}" for row in rows)


def render_support_matrix(smoke: dict[str, Any], required_rows: list[str]) -> str:
    statuses = _flatten_manual_matrix(smoke.get("manual_matrix", {}))
    required_present = [statuses.get(row, "missing") for row in required_rows]
    required_pass = sum(1 for status in required_present if status == "pass")
    lines = [
        "# Generated Support Matrix",
        "",
        "<!-- generated by scripts/generate_support_matrix.py; do not edit by hand -->",
        "",
        f"Source smoke artifact: `{smoke.get('tag', 'unknown')}`.",
        f"Required release rows: {required_pass}/{len(required_rows)} pass.",
        "",
        "| Claim | Status | Evidence rows |",
        "| --- | --- | --- |",
    ]
    for claim, rows in SUPPORT_CLAIMS:
        claim_statuses = [statuses.get(row, "missing") for row in rows]
        lines.append(f"| {claim} | {_claim_status(claim_statuses)} | {_row_summary(rows, statuses)} |")
    missing_required = [row for row in required_rows if statuses.get(row) != "pass"]
    lines.extend(["", "## Required Row Exceptions", ""])
    if missing_required:
        for row in missing_required:
            lines.append(f"- `{row}`: {statuses.get(row, 'missing')}")
    else:
        lines.append("- None. Every required row is marked `pass` in the source smoke artifact.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--smoke", default="release-smoke-v0.4.0.json")
    parser.add_argument("--required", default="tests/fixtures/release_required_rows_v2.json")
    parser.add_argument("--output", default="docs/support_matrix.generated.md")
    args = parser.parse_args()

    smoke = json.loads(Path(args.smoke).read_text(encoding="utf-8"))
    required = json.loads(Path(args.required).read_text(encoding="utf-8"))["rows"]
    Path(args.output).write_text(render_support_matrix(smoke, required), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
